### PR TITLE
Mute when people wonder where emoji have gone

### PR DESCRIPTION
**Pull request by s5bug**
I'm guessing you have already heard about this from Wolfiri, and I would've done it sooner if I had known b1nb0t was open source.

### CODE REVIEW

**Comment by s5bug** [comment]
capture

Test on the Apple Emoji server I made.

**Comment by s5bug** [comment]
Changes requested: change capitalization on readRules and use event.msg.reply

**Comment by s5bug** [comment]
Changes requested: Have b1nb0t mute personally. Working on currently.

**Comment by slice** [comment]
1. Why `Plugin.spawn_later(self` instead of `self.spawn_later`?
2. I can't really tell, but are you modifying the default testing role/channel IDs? I don't think B1n will like that.

**Comment by s5bug** [comment]
b1nzy said to use `Plugin.spawn_later` although `self.spawn_later` makes more sense. I don't know much about selfs in python.

No, there's a testing section and a production section in the code, the production section has the correct IDs.

**Comment by s5bug** [comment]
Whoops, no commit msg. I just changed it to use self.

**Comment by slice** [comment]
> b1nzy said to use `Plugin.spawn_later`

He was referring to the `spawn_later` method of `Plugin`, which you call on `self`.

**Comment by s5bug** [comment]
I don't use python often, so I really don't know all this self stuff and why it works.

**Comment by SuperSajuuk** [comment]
Self is used in classes, it means itself. If you are used to languages like PHP or JS, self is essentially things like $this-> or "this" when talking about the calling of the instance.

**Comment by s5bug** [comment]
Yeah, I inferred that from slice's comment and the other methods that PyCharm screwed up. (It gave the wrong message signature.)

**Pull request closed without merging**
